language: python
python:
  - "3.5"
sudo: false
cache:
  directories:
  - "build"
  - "$HOME/.cache/pip"
before_script:
  - pip install codecov
script:
  - coverage run setup.py test
after_success:
  - codecov
