#!/usr/bin/env python3

import argparse
from validation_components.validation import validation_runner

parser = argparse.ArgumentParser()
parser.add_argument('spreadsheet', type=str,
					help='Manifest spreadsheet to be checked for matching taxon and common name')
args = parser.parse_args()
validation_runner(args)

	# TODO: Add connection error exceptions
	# TODO: Add parser and main function testing
